name: rails-ec

services:
  app:
    build:
      context: ../
      dockerfile: .infra/local/app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    tty: true
    volumes:
      - ../:/app:cached

  db:
    build: 
      context: ../.infra/local/db
      dockerfile: Dockerfile
    platform: linux/x86_64
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      interval: 2s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - ../.infra/local/db/data:/var/lib/postgresql
      - ../.infra/local/db/postgresql.conf:/etc/postgresql/postgresql.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
